- name: Check the status
  hosts: localhost
  tasks:
    - name: Book Info status
      command: "kubectl get pods -n default"
      register: pods_status
    - debug: 
         msg: "{{ pods_status.stdout }}"
